"""
MODEL-03 - Pure Real (Mega Dataset).
"""

import os

_model_file = __file__
_base = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(_model_file)), "..", "simulationconfig.py"))
__file__ = _base
exec(open(_base, encoding="utf-8").read())
__file__ = _model_file

TARGET_POINT_EXPERIMENT_PREFIX = "model_03_pure_real"

TARGET_POINT_MANIFEST_ROOT = os.path.join(CAR_PATH, "data", "sim_multitrack", "index")
TARGET_POINT_EXTERNAL_ROOT = os.path.join(CAR_PATH, "data", "datasets", "mega_dataset", "tubs")
TARGET_POINT_EXTERNAL_DATA_RATIO = 1.0
TARGET_POINT_EXTERNAL_ONLY = True

TARGET_POINT_IMAGE_W = 128
TARGET_POINT_IMAGE_H = 128
TARGET_POINT_BATCH_SIZE = 384
TARGET_POINT_MAX_EPOCHS = 30
TARGET_POINT_EARLY_STOP_PATIENCE = 5

TARGET_POINT_USE_TFDATA = True
TARGET_POINT_TFDATA_SHUFFLE_BUFFER = 65536
TARGET_POINT_TFDATA_THREADPOOL_SIZE = 24
TARGET_POINT_MAX_VAL_SAMPLES = 40000
TARGET_POINT_INTERLEAVE_TRAIN_SAMPLES = False
TARGET_POINT_ENABLE_AUGMENTATION = False
TARGET_POINT_STEERING_BALANCE_FLIP_ENABLED = False

TARGET_POINT_PRECISION_POLICY = "mixed_float16"
TARGET_POINT_ENABLE_XLA = True
TARGET_POINT_STEPS_PER_EXECUTION = 128
TARGET_POINT_FIT_WORKERS = 12
TARGET_POINT_FIT_USE_MULTIPROCESSING = False
TARGET_POINT_FIT_MAX_QUEUE_SIZE = 64

TARGET_POINT_FULL_DIAGNOSTICS = False
TARGET_POINT_DIAG_TRAIN_SAMPLES = 3000
TARGET_POINT_DIAG_VAL_SAMPLES = 3000
TARGET_POINT_DIAG_TRACK_SAMPLES = 6000
