"""
MODEL-02 - Pure Sim + Domain Randomization.
"""

import os

_model_file = __file__
_base = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(_model_file)), "..", "simulationconfig.py"))
__file__ = _base
exec(open(_base, encoding="utf-8").read())
__file__ = _model_file

TARGET_POINT_EXPERIMENT_PREFIX = "model_02_sim_domain_randomization"

TARGET_POINT_MANIFEST_ROOT = os.path.join(CAR_PATH, "data", "sim_multitrack", "index")
TARGET_POINT_EXTERNAL_ROOT = None
TARGET_POINT_EXTERNAL_DATA_RATIO = 0.0
TARGET_POINT_EXTERNAL_ONLY = False

TARGET_POINT_IMAGE_W = 128
TARGET_POINT_IMAGE_H = 128
TARGET_POINT_BATCH_SIZE = 256
TARGET_POINT_MAX_EPOCHS = 30
TARGET_POINT_EARLY_STOP_PATIENCE = 5

TARGET_POINT_USE_TFDATA = False
TARGET_POINT_ENABLE_AUGMENTATION = True
TARGET_POINT_AUG_CLIP_FRAMES = 5
TARGET_POINT_AUG_BRIGHTNESS_LIMIT = 0.40
TARGET_POINT_AUG_CONTRAST_LIMIT = 0.30
TARGET_POINT_AUG_BLUR_RADIUS_MAX = 3.5
TARGET_POINT_AUG_RGB_SHIFT_MAX = 24
TARGET_POINT_AUG_SHIFT_PX_MAX = 10.0
TARGET_POINT_AUG_ROTATION_DEG_MAX = 6.0
TARGET_POINT_AUG_PERSPECTIVE_PX_MAX = 10.0
TARGET_POINT_AUG_LABEL_SHIFT_M_PER_PX = 0.010
TARGET_POINT_AUG_ROTATION_LABEL_GAIN = 0.75
TARGET_POINT_AUG_RECOVERY_LABEL_SCALE = 1.25

TARGET_POINT_STEERING_BALANCE_FLIP_ENABLED = True
TARGET_POINT_STEERING_BALANCE_POS_FLIP_PROB = 0.50
TARGET_POINT_STEERING_BALANCE_NEG_FLIP_PROB = 0.50

TARGET_POINT_PRECISION_POLICY = "mixed_float16"
TARGET_POINT_ENABLE_XLA = True
TARGET_POINT_STEPS_PER_EXECUTION = 64
TARGET_POINT_FIT_WORKERS = 12
TARGET_POINT_FIT_USE_MULTIPROCESSING = False
TARGET_POINT_FIT_MAX_QUEUE_SIZE = 64

TARGET_POINT_FULL_DIAGNOSTICS = False
TARGET_POINT_DIAG_TRAIN_SAMPLES = 3000
TARGET_POINT_DIAG_VAL_SAMPLES = 3000
TARGET_POINT_DIAG_TRACK_SAMPLES = 6000
